services:
  # 1. The Frontend Web Service (Public Facing)
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/recipeai/Dockerfile
    dockerContext: ./frontend/recipeai
    # Nginx proxy_pass will use this internal URL
    # The backend service name is 'backend' (defined below)
    # and Render exposes it on port 8080.
    envVars:
      - key: NGINX_PROXY_PASS
        value: http://backend:8080

  # 2. The PostgreSQL Database Service (Docker Container)
  - type: pserv
    name: postgres-db
    env: docker
    dockerfilePath: ./postgres/Dockerfile
    dockerContext: ./postgres
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
    envVars:
      - key: POSTGRES_DB
        value: recipeai
      - key: POSTGRES_USER
        value: recipe_user
      - key: POSTGRES_PASSWORD
        value: recipe_password_123

  # 3. The Backend Private Service (Internal)
  - type: pserv # 'pserv' means Private Service
    name: backend
    env: docker
    dockerfilePath: ./backendApi/Dockerfile
    dockerContext: ./backendApi
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: POSTGRES_URL
        value: jdbc:postgresql://postgres-db:5432/recipeai
      - key: POSTGRES_USER
        value: recipe_user
      - key: POSTGRES_PASSWORD
        value: recipe_password_123
      - key: GEMINI_API_KEY
        sync: false # This is a secret, man change It and send 