server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location ~* ^/(?:.*(?:\.env(?:$|[._-])|\.tfstate(?:\.backup)?$|\.tfvars$|\.(?:log|sql|bak|backup)$)|(?:.*/)?(?:wp-content(?:/.*|$)|wp-json(?:/.*|$)|wp-config\.php$|xmlrpc\.php$|serverless\.ya?ml|vercel\.json|netlify\.toml|docker-compose\.ya?ml|amplify\.ya?ml|stripe\.env|stripe(?:-keys|-credentials)?\.json|sendgrid\.env)$) {
        return 404;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}
